version: 2

sources:
  - name: raw_data
    description: Raw Spotify listening history data loaded from Airflow
    database: tempo_warehouse
    schema: raw_data
    tables:
      - name: listening_history
        description: Raw JSON data from Spotify API
        columns:
          - name: id
            description: Primary key
            tests:
              - unique
              - not_null
          - name: extraction_timestamp
            description: When the data was extracted from Spotify
            tests:
              - not_null
          - name: raw_data
            description: Raw JSONB payload from Spotify API
            tests:
              - not_null
